# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure git credentials
      # You may pin to the exact commit or the version.
      # uses: OleksiyRudenko/gha-git-credentials@6132cfce45156e2c1562673f9be1a91a575ce879
      uses: OleksiyRudenko/gha-git-credentials@v2-latest
      with:
        global: true
        name: 'Daniel Rdz'
        email: 'danymar24@gmail.com'
        actor: 'DanielRdz'
        username: 'danymar24'
        token: '${{ secrets.TOKEN }}'
    - name: Use Node.js 14.
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: git config user.name "$GITHUB_ACTOR"
    - run: git config user.email "${GITHUB_ACTOR}@bots.github.com"
    - run: npm ci
    - run: npm run build
